name: CF Anac Oferta Demanda Aerea CI/CD Deploy

on:
  push:
    branches:
      - main
    paths:
      - "cloudfunctions/src/cf_extract_anac_oferta_demanda_aerea_to_bronze/**"
      - ".github/workflows/ci-deploy-cloudfunctions-anac-oferta-demanda-aerea.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Set up Cloud SDK
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Cloud Functions
        run: |
          cd cloudfunctions/src
          . cf_extract_anac_oferta_demanda_aerea_to_bronze/var.sh
          sh cf_extract_anac_oferta_demanda_aerea_to_bronze/deploy.sh
